/vis/open OGL
/control/saveHistory

#/vis/verbose errors
/vis/viewer/set/background white
/vis/geometry/set/colour all -1 0 0 0
/vis/drawVolume worlds
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
/vis/scene/add/axes


/vis/geometry/set/colour cylinder 0 0.5 0.5 0.5
/vis/geometry/set/forceSolid cylinder
/vis/geometry/set/colour cylinder_with_hole 0 0.5 0.5 0.5
/vis/geometry/set/forceSolid cylinder_with_hole
/vis/scene/add/date
/vis/scene/add/hits


